export const userConfig = {
  prejoinPageEnabled: false,
  toolbarButtons: [
    "camera",
    "closedcaptions",
    "desktop",
    "etherpad",
    "feedback",
    "filmstrip",
    "help",
    "microphone",
    "participants-pane",
    "profile",
    "raisehand",
    "select-background",
    "shareaudio",
    "sharedvideo",
    "shortcuts",
    "tileview",
    "toggle-camera",
    "__end",
  ],
};
export const adminConfig = {
  prejoinPageEnabled: false,
  toolbarButtons: [
    "camera",
    "closedcaptions",
    "desktop",
    "download",
    "embedmeeting",
    "etherpad",
    "feedback",
    "filmstrip",
    "fullscreen",
    "help",
    "invite",
    "livestreaming",
    "microphone",
    "mute-everyone",
    "mute-video-everyone",
    "participants-pane",
    "profile",
    "raisehand",
    "recording",
    "security",
    "select-background",
    "settings",
    "shareaudio",
    "sharedvideo",
    "shortcuts",
    "stats",
    "tileview",
    "toggle-camera",
    "videoquality",
    "__end",
  ],
};
